import {
  COMMAND_BY_ID,
  SECTION_LABELS,
  ScriptModel,
  ScriptStep,
  SECTION_ORDER,
} from './catalog';

export interface GeneratedScript {
  /** Full input text ready to save as in.lammps */
  text: string;
  /** Emitted (non-empty) command lines with their originating step uid. */
  emitted: { uid: string; line: string }[];
  /** Non-fatal issues: empty required params, disabled steps, etc. */
  warnings: string[];
}

const isFilled = (v: string | undefined): boolean =>
  v !== undefined && v.trim() !== '';

/**
 * Render the script for a model.
 *
 * Rules:
 * - MANUAL OVERRIDE: when model.manualText is set to non-empty text, it is
 *   emitted verbatim and the step list is bypassed (a warning says so).
 * - Steps are grouped by section in canonical order; within a section the
 *   user's order is preserved.
 * - Disabled steps are skipped SILENTLY (the flowchart shows them dashed);
 *   only structurally broken steps produce warnings.
 * - Steps whose required params are blank are skipped + warned about.
 * - A header comment block documents title, generator, and section banners.
 */
export const generateScript = (model: ScriptModel): GeneratedScript => {
  if (model.manualText !== undefined && model.manualText.trim() !== '') {
    return {
      text: model.manualText,
      emitted: [],
      warnings: [
        'Manual edit mode — the builder step list is bypassed. ' +
          'Exit manual editing to regenerate from your steps.',
      ],
    };
  }

  const warnings: string[] = [];
  const emitted: { uid: string; line: string }[] = [];
  const chunks: string[] = [];

  chunks.push(
    '# ----------------------------------------------------------------',
    `# ${model.title || 'LAMMPS simulation'}`,
    '# Generated by Molecule3D — LAMMPS Workbench by Shuvam Banerji Seal',
    `# ${new Date().toISOString().slice(0, 10)}`,
    '# ----------------------------------------------------------------',
    ''
  );

  const bySection = new Map<string, ScriptStep[]>();
  for (const step of model.steps) {
    if (!step.enabled) continue;
    const def = COMMAND_BY_ID[step.defId];
    if (!def) {
      warnings.push(`Unknown command id "${step.defId}" — step skipped.`);
      continue;
    }
    const list = bySection.get(def.section) ?? [];
    list.push(step);
    bySection.set(def.section, list);
  }

  let firstSection = true;
  for (const section of SECTION_ORDER) {
    const steps = bySection.get(section);
    if (!steps || steps.length === 0) continue;

    if (!firstSection) chunks.push('');
    chunks.push(`# ---- ${SECTION_LABELS[section]} ----`);
    firstSection = false;

    for (const step of steps) {
      const def = COMMAND_BY_ID[step.defId];
      if (step.note?.trim()) chunks.push(`# ${step.note.trim()}`);

      // Required-param check
      const missing = def.params.filter(
        pd => pd.type !== 'flag' && !isFilled(step.params[pd.key]) && isRequired(def.id, pd.key)
      );
      if (missing.length > 0) {
        warnings.push(
          `${def.label}: missing ${missing.map(m => m.label).join(', ')} — skipped.`
        );
        continue;
      }

      const lines = def.build(step.params).filter(l => l.trim() !== '');
      for (const l of lines) {
        chunks.push(l);
        emitted.push({ uid: step.uid, line: l });
      }
    }
  }

  chunks.push('');
  chunks.push('# End of generated input');
  chunks.push('');

  return { text: chunks.join('\n'), emitted, warnings };
};

/** Params that must be non-empty per command (beyond ParamDef.required). */
const REQUIRED: Record<string, string[]> = {
  'read_data': ['file'],
  'read_restart': ['file'],
  'create_box': ['ntypes', 'region'],
  'region_block': ['id'],
  'region_sphere': ['id'],
  'region_cylinder': ['id'],
  'region_prism': ['id'],
  'create_bonds': ['args'],
  'change_box': ['args'],
  'read_dump': ['file', 'fields'],
  'molecule_cmd': ['file'],
  'pair_style_hybrid': ['substyles'],
  'pair_write': ['args'],
  'write_dump': ['fields'],
  'fix_ave_time': ['values'],
  'fix_ave_histo': ['values'],
  'fix_print_out': ['text'],
  'compute_reduce': ['input'],
  'fix_move': ['args'],
  'fix_modify_cmd': ['fixid'],
  'compute_modify': ['compid'],
  'unfix_cmd': ['fixid'],
  'undump_cmd': ['dumpid'],
  'uncompute_cmd': ['compid'],
  'variable_atom': ['name', 'expr'],
  'if_cmd': ['condition', 'thenBlock'],
  'label_cmd': ['id'],
  'jump_cmd': ['file'],
  'next_cmd': ['vars'],
  'include_cmd': ['file'],
  'shell_cmd': ['cmd'],
};

const isRequired = (defId: string, key: string): boolean =>
  (REQUIRED[defId] ?? []).includes(key);

/* ------------------------------------------------------------------ */
/* Flowchart derivation                                                */
/* ------------------------------------------------------------------ */

export interface FlowNode {
  uid: string;
  defId: string;
  label: string;
  sublabel: string;
  section: string;
  enabled: boolean;
}

export interface FlowEdge {
  from: string;
  to: string;
}

export interface FlowGraph {
  start: boolean;
  end: boolean;
  nodes: FlowNode[];
  edges: FlowEdge[];
}

/**
 * Derive a linear pipeline graph from the model. Disabled steps appear as
 * dashed nodes so the user can see what they switched off.
 */
export const deriveFlowchart = (model: ScriptModel): FlowGraph => {
  const nodes: FlowNode[] = [];
  const edges: FlowEdge[] = [];

  const active = model.steps.filter(s => COMMAND_BY_ID[s.defId]);
  active.forEach((step, i) => {
    const def = COMMAND_BY_ID[step.defId];
    nodes.push({
      uid: step.uid,
      defId: step.defId,
      label: def.command === 'fix' ? fixLabel(def.id, step) : def.command,
      sublabel: shortParams(def, step),
      section: def.section,
      enabled: step.enabled,
    });
    if (i > 0) edges.push({ from: active[i - 1].uid, to: step.uid });
  });

  return { start: nodes.length > 0, end: nodes.length > 0, nodes, edges };
};

const fixLabel = (defId: string, _step: ScriptStep): string => {
  // fix.<style> ids encode the style for readability
  return `fix ${defId.split('.')[1] ?? ''}`.trim();
};

const shortParams = (
  def: import('./catalog').CommandDef,
  step: ScriptStep
): string => {
  const parts: string[] = [];
  for (const pd of def.params.slice(0, 3)) {
    const v = step.params[pd.key];
    if (v && v.trim()) parts.push(String(v).slice(0, 18));
  }
  return parts.join(' · ');
};
